### ISSUE TITLE
Docker 1.12

### ISSUE THREAD

**Issue by BarnumD** [scotty-c/puppet-docker_swarm#2]
It doesn't seem like this module supports the new way of doing clusters with docker swarm without a third party back-end (circa docker 1.12. )  Is there any plan to support this configuration?

**Comment by scotty-c** [comment]
Hey @BarnumD This module supports leagacy swarm. So enigine 1.11 and below. As in the new engine swarm mode in built in, no longer external. It is probally best that it lives in the Docker module https://github.com/garethr/garethr-docker. If you watch that repo there should be a realse with Swarm mode coming soon.
